### PR TITLE
Update excelhandler.py

### PR DESCRIPTION
**Pull request by ouyangyangyang**
+ one line
+ one line
+ one line

### CODE REVIEW

**Comment by ouyangyangyang** [comment]
## what are this? ##

**Comment by ouyangyangyang** [comment]
*Reopen the pull requests*

**Comment by itongworld** [comment]
**I locked the conversation on this pull request**

**Comment by itongworld** [comment]
**I agreed with the commit from ouyangyangyang:patch-1 into the base branch itongworld:master.**

**Pull request merged**
